### PR TITLE
Switch kamon-spm to 1.1.x version

### PR DESCRIPTION
**Pull request by qkoshelev**

### CODE REVIEW

**Comment by otisg** [comment]
@ivantopo any chance you could review/merge?

**Comment by otisg** [comment]
There's also https://github.com/kamon-io/kamon.io/pull/44 for the site/docs.

**Comment by dpsoft** [comment]
@qkoshelev @otisg sorry for the late response,  I'm going to be able to review/merge this PR in a couple of hours

**Comment by dpsoft** [comment]
Guys @qkoshelev @otisg , what do you think if we add as collaborators in this repository?

**Comment by otisg** [comment]
Probably wouldn't hurt, though somebody else from Sematext is likely to take over the kamon-spm maintenance in the future.

**Comment by ivantopo** [comment]
Hey @otisg, we just invited you and @qkoshelev to be part of the org and a team with write access to this repository. Feel free to push anything you might need! You will still need to ping us to run a release, though.

**Comment by dpsoft** [comment]
@otisg @qkoshelev  https://github.com/kamon-io/kamon-spm/releases/tag/v1.1.1 published on our bintray repo and on its way to Maven Central

**Pull request merged**
