### PR TITLE
Update AsyncHttpClient version to 2.5.2

### PR DESCRIPTION
**Pull request by sivasamyk**
- Update AsyncHttpClient lib version to 2.5.2 to fix 
```
Exception in thread "loaded-from-config: kamon.spm.SPMReporter" java.lang.IllegalAccessError: tried to access field io.netty.handler.ssl.JdkSslContext.SUPPORTED_CIPHERS from class
```
- Update version to 1.1.2
- Update README to reflect 1.x config & latest SPM links

### CODE REVIEW

**Comment by sivasamyk** [comment]
@ivantopo could you please review/merge this PR?

**Comment by otisg** [comment]
Or @dpsoft perhaps?

**Comment by dpsoft** [comment]
Hey @sivasamyk @otisg , this looks good to me, thanks a lot for the contribution! Only pending thing would be for @sivasamyk to [electronically sign](https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform) the CLA and we can merge and publish this :tada:

**Comment by sivasamyk** [comment]
@dpsoft I signed the CLA.

**Comment by dpsoft** [comment]
@sivasamyk @otisg done: https://github.com/kamon-io/kamon-spm/releases/tag/v1.1.2

**Pull request merged**
